spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      # discovery需要时再配置，以上为必须配置项
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        serviceName: consul-service
        healthCheckinterval: 20s
        tags: foo=bar, baz